<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="{{asset('static/css/3.0.3_normalize.min.css')}}">
    <link rel="stylesheet" href="{{asset('static/css/2.3.2_hint.min.css')}}">
    <link rel="stylesheet" href="{{asset('static/css/3.3.6_iconfonts.min.css')}}">
    <style type="text/css">
        *{margin:0;padding:0;border:0;outline:0}*,:after,:before{box-sizing:border-box}html{font-size:14px;font-family:Helvetica Neue,Microsoft YaHei,arial,sans-serif;line-height:1}body,html{height:100%}a{color:inherit;text-decoration:none;cursor:pointer}li{list-style:none}.transition{transition:all .3s}.ellipsis{text-overflow:ellipsis;white-space:nowrap;overflow:hidden}.clearfix{zoom:1}.clearfix:after{content:".";display:block;height:0;visibility:hidden;clear:both}.fl{float:left}.fr{float:right}@keyframes fade-in{0%{opacity:0}to{opacity:1}}@keyframes fade-out{0%{opacity:1}to{opacity:0}}.fade-enter-active{animation:fade-in .3s}.fade-leave-active{animation:fade-out .3s}@keyframes drop-in{0%{transform:translate3d(-10px,0,0) scale(.9);opacity:0}to{transform:translateZ(0) scale(1);opacity:1}}@keyframes drop-out{0%{transform:translateZ(0) scale(1);opacity:1}to{transform:translate3d(-10px,0,0) scale(.9);opacity:0}}.drop-enter-active{animation:drop-in .3s}.drop-leave-active{animation:drop-out .3s}.eqc-btn{display:inline-block;padding:0 12px;font-size:14px;text-align:center;border-radius:3px;transition:all .3s;cursor:pointer}.eqc-btn.blue{color:#fff;background:#1593ff;border:1px solid #1593ff}.eqc-btn.blue:hover{background:#198ae7;border:1px solid #198ae7}.eqc-btn.red{color:#fff;background:#ff2a6a;border:1px solid #ff2a6a}.eqc-btn.red:hover{background:#ff004d;border:1px solid #ff2a6a}.eqc-btn.white{color:#666;background:#fff;border:1px solid #ccd5db}.eqc-btn.white:hover{color:#1593ff;border:1px solid #1593ff}.eqc-btn.disable{color:#999;background:#eee;border:1px solid #eee;cursor:not-allowed}.eqc-btn.h36{height:36px;line-height:34px}.eqc-dialog{position:relative;background:#fff;overflow:hidden;box-shadow:0 0 16px 0 rgba(0,0,0,.16)}.eqc-dialog>.head{display:flex;align-items:center;height:56px;background:#f7f7f7}.eqc-dialog>.head>.title{line-height:1;margin-left:20px;font-size:16px}.eqc-dialog>.head>.close{position:absolute;top:16px;right:20px;font-size:22px;cursor:pointer;transition:all .3s}.eqc-dialog>.head>.close:hover{color:#ff2a6a}.eqc-meterial{position:relative;width:960px;height:600px;cursor:default;background:#fff;box-shadow:0 0 16px 0 rgba(0,0,0,.16);overflow:hidden}.eqc-meterial .eqc-content{position:relative;width:calc(100% - 176px);height:100%;float:left}.eqc-meterial .eqc-content .blur{filter:blur(5px)}
    </style>
    <style type="text/css">
        .eqc-container{display:flex;align-items:center;justify-content:center;height:100%}.eqc-container .mask{position:fixed;top:0;left:0;bottom:0;right:0;background:rgba(0,0,0,.6)}
    </style>
    <style type="text/css">
        .eqc-nav{position:relative;width:176px;height:100%;color:#fff;background:#212121;float:left}.eqc-nav .head{position:relative;height:60px;line-height:60px;padding-left:28px;z-index:3}.eqc-nav .head .title{font-size:18px;font-weight:700}.eqc-nav .head .tip{display:inline-block;margin-left:10px;line-height:1}.eqc-nav .head .tip .icon{font-size:16px;transition:all .3s}.eqc-nav .head .tip .tip-box{display:inline-block;position:absolute;top:14px;padding-left:30px;z-index:2;opacity:0;pointer-events:none;transition:all .3s}.eqc-nav .head .tip .tip-box .desc{position:relative;width:352px;padding:0 6px;font-size:12px;line-height:34px;color:#fff;background:rgba(0,0,0,.9);box-shadow:0 0 16px 0 rgba(0,0,0,.16);border-radius:3px}.eqc-nav .head .tip .tip-box .desc .agreement{color:#1593ff;cursor:pointer}.eqc-nav .head .tip .tip-box .desc:before{position:absolute;left:-6px;top:10px;content:"";border:6px solid transparent;border-right:6px solid rgba(0,0,0,.7);border-left:0}.eqc-nav .head .tip:hover .icon{color:#1593ff}.eqc-nav .head .tip:hover .tip-box{opacity:1;pointer-events:unset}.eqc-nav .menu{margin-top:8px}.eqc-nav .menu>li{line-height:48px;padding-left:28px;cursor:pointer;transition:all .3s}.eqc-nav .menu>li.active,.eqc-nav .menu>li:hover{font-weight:700;background:#1593ff}.eqc-nav .coupon{margin-top:24px}.eqc-nav .coupon>li{width:152px;height:40px;margin:auto}.eqc-nav .coupon>li:not(:last-child){margin-bottom:8px}.eqc-nav .coupon>li a{display:block;height:100%;background:no-repeat 50%/cover}.eqc-nav>.tip{position:absolute;left:0;bottom:60px;padding:14px 16px;line-height:1.5;font-size:12px;opacity:.6}.eqc-nav .fun{position:absolute;bottom:0;left:0;width:100%}.eqc-nav .fun>li{line-height:60px;text-align:center}
    </style>
    <style type="text/css">
        .eqc-nav-mobile-load{margin-bottom:10px}.eqc-nav-mobile-load .upload-btn{position:relative;background:#1bc7b1;cursor:pointer;transition:all .3s;line-height:40px;margin:auto;width:120px;border-radius:20px}.eqc-nav-mobile-load .upload-btn:hover{background:#00b49d}.eqc-nav-mobile-load .upload-btn .icon{font-size:16px;vertical-align:middle}.eqc-nav-mobile-load .upload-btn .tip{line-height:16px;vertical-align:middle}.eqc-nav-mobile-load .qrcode-container{position:absolute;left:174px;top:-114px;width:200px;height:210px;padding:10px;color:gray;background-color:#fff;border-radius:3px;box-shadow:0 2px 8px 0 rgba(0,0,0,.15);z-index:1;transform-origin:left center}.eqc-nav-mobile-load .qrcode-container h5{margin-top:5px;height:20px;line-height:20px}.eqc-nav-mobile-load .qrcode-container .qrcode-el{display:flex;justify-content:center;align-items:center;height:170px;width:180px}.eqc-nav-mobile-load .qrcode-container .triangle{position:absolute;left:-30px;top:120px;width:0;height:0;border-width:15px;border-style:dashed solid dashed dashed;border-color:transparent #fff transparent transparent}
    </style>
    <style type="text/css">
        .eqc-nav-upload{margin-bottom:10px}.eqc-nav-upload .upload-btn{display:inline-block;margin-left:29px;position:relative;background:#1593ff;cursor:pointer;transition:all .3s;line-height:40px;width:120px;border-radius:20px;margin:auto}.eqc-nav-upload .upload-btn:hover{background:#198ae7}.eqc-nav-upload .upload-btn .progress{position:absolute;left:0;height:100%;background:rgba(0,0,0,.2);width:0;transition:all .3s;border-radius:20px}.eqc-nav-upload .upload-btn .icon,.eqc-nav-upload .upload-btn .tip{position:relative;vertical-align:middle}.eqc-nav-upload .upload-btn .icon{font-size:16px}.eqc-nav-upload .upload-btn .tip{line-height:16px}.eqc-nav-upload .tipIcon{width:28px;height:16px;display:inline-block;position:absolute;margin-top:12px;transition:all .3s;line-height:16px}.eqc-nav-upload .tipIcon .iconW{font-size:16px;transition:all .3s}.eqc-nav-upload .tipIcon .tip-box{display:inline-block;position:absolute;margin-left:11px;bottom:-22px;z-index:2;opacity:0;pointer-events:none;transition:all .3s;text-align:left;background:rgba(0,0,0,.9)}.eqc-nav-upload .tipIcon .tip-box .desc{display:block;width:400px;height:165px;position:relative;padding:16px;font-size:12px;line-height:18px;color:#fff;box-shadow:0 0 16px 0 rgba(0,0,0,.16);border-radius:3px}.eqc-nav-upload .tipIcon .tip-box .desc .agreement{color:#1593ff;cursor:pointer}.eqc-nav-upload .tipIcon .tip-box .desc:before{position:absolute;left:-6px;bottom:22px;content:"";border:6px solid transparent;border-right:6px solid rgba(0,0,0,.9);border-left:0}.eqc-nav-upload .tipIcon:hover .iconW{color:#1593ff}.eqc-nav-upload .tipIcon:hover .tip-box{opacity:1;pointer-events:unset}
    </style>
    <style type="text/css">
        .eqc-head-sys .head-top{position:relative;height:60px;line-height:60px;padding:0 28px;box-shadow:0 6px 6px 0 rgba(0,0,0,.16);z-index:1}.eqc-head-sys .head-top .list{display:inline-block}.eqc-head-sys .head-top .list>.item{display:inline-block;height:60px;color:#333;border-bottom:2px solid #fff;cursor:pointer;transition:all .3s}.eqc-head-sys .head-top .list>.item:not(:first-child){margin-left:40px}.eqc-head-sys .head-top .list>.item.active,.eqc-head-sys .head-top .list>.item:hover{color:#1593ff;border-bottom:2px solid #1593ff}.eqc-head-sys .head-top .icon{width:22px;height:22px;line-height:22px;margin:19px 16px;text-align:center;font-size:18px;cursor:pointer;transition:all .3s}.eqc-head-sys .head-top .icon.search{width:50px;text-align:justify}.eqc-head-sys .head-top .icon.search span{margin-left:2px;font-size:14px;position:absolute}.eqc-head-sys .head-top .icon.search:hover{color:#1593ff}.eqc-head-sys .head-top .icon.close{margin-right:0;font-size:22px}.eqc-head-sys .head-top .icon.close:hover{color:#ff2a6a}.eqc-head-sys .head-bottom{padding:16px 28px;font-size:13px}.eqc-head-sys .head-bottom .bottom-down,.eqc-head-sys .head-bottom .bottom-up{height:36px;line-height:36px}.eqc-head-sys .head-bottom .name{color:#666;margin-right:6px}.eqc-head-sys .head-bottom .price{margin-left:30px}.eqc-head-sys .head-bottom .list{display:inline-block}.eqc-head-sys .head-bottom .list .item{display:inline-block;position:relative;margin-right:18px;cursor:pointer;transition:all .3s}.eqc-head-sys .head-bottom .list .item.active,.eqc-head-sys .head-bottom .list .item:hover{color:#1593ff}.eqc-head-sys .head-bottom .list .item.active:after,.eqc-head-sys .head-bottom .list .item:hover:after{content:"|";color:#333}.eqc-head-sys .head-bottom .list .item:after{content:"|";position:absolute;right:-10px;bottom:2px;font-weight:700;pointer-events:none}.eqc-head-sys .head-bottom .list .item:last-child:after{content:""}
    </style>
    <style type="text/css">
        .eqc-image-list{height:calc(100% - 60px)}.eqc-image-list.sys{height:calc(100% - 60px - 104px)}.eqc-image-list.sys .wrap .list{padding-top:0}.eqc-image-list.sys.no-sub,.eqc-image-list.tag{height:calc(100% - 60px - 68px)}.eqc-image-list.tag .wrap .list{padding-top:0}.eqc-image-list.tag-manage{position:relative;top:68px;width:100%;height:calc(100% - 60px - 68px);background:#fff;z-index:0}.eqc-image-list .wrap{position:relative;height:100%}.eqc-image-list .wrap .list{padding:28px}.eqc-image-list .wrap .complete{padding:0 28px}
    </style>
    <style type="text/css">
        .eqc-list-status{display:flex;align-items:center;justify-content:center;height:100%;font-size:16px}.eqc-list-status .result{text-align:center}.eqc-list-status .result .box{width:240px;height:240px;margin:auto;background:url(//m.kameimei.cn/material/images/box.svg)}.eqc-list-status .result .msg{line-height:1.2em}
    </style>
	<script type="text/javascript" src="{{asset('static/js/qiniu-js-sdk/1.0.14-beta/qiniu.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('static/js/plupload/2.1.8/plupload.full.min.js')}}"></script>
</head>

<body>
<div class="eqc-container">
    <div class="mask"></div> 
    <div class="eqc-meterial">
        <div class="eqc-nav"><div class="head"><span class="title">图片库</span> <div class="tip"><i class="icon eqf-info-f"></i> <div class="tip-box"><div class="desc">
        使用图片即代表同意并接受
        <span class="agreement">《大喜帖图片版权许可与服务协议》</span>
        </div></div></div></div> <ul class="menu"><li class="">我的图片</li> <li class="active">图片</li></ul> <ul class="coupon"><li></li></ul>  <ul class="fun"><!----> <li id="upload_container" class="upload eqc-nav-upload" style="line-height: 0px; position: relative;"><div id="upload_btn" class="upload-btn" style="z-index: 1;"><div class="progress"></div> <i class="icon eqf-cloudupload-f"></i> <span class="tip">本地上传</span></div> <div class="tipIcon"><span class="iconW eqf-why-f"></span> <div class="tip-box"><span class="desc"><p style="font-size: 16px; padding-bottom: 12px;">上传须知</p> <p style="padding-bottom: 12px;">大喜帖为广大用户提供原创图片上传渠道、信息储存空间等网络技术服务，用户可在遵守<span class="agreement">《大喜帖图片版权许可与服务协议》</span>的前提下自行上传并对其上传作品承担全部责任，请谨慎使用上传功能。</p> <p>通过本地电脑上传图片，大小不超过3M，支持格式：JPG、PNG、GIF，一次最多上传20张。</p></span></div></div><div id="html5_1hepf3t7k73c1ont1s031op3jdp3_container" class="moxie-shim moxie-shim-html5" style="position: absolute; top: 0px; left: 28px; width: 120px; height: 40px; overflow: hidden; z-index: 0;"><input id="html5_1hepf3t7k73c1ont1s031op3jdp3" type="file" style="font-size: 999px; opacity: 0; position: absolute; top: 0px; left: 0px; width: 100%; height: 100%;" multiple="" accept="image/jpeg,.jpg,image/gif,.gif,image/png,.png,.jpeg"></div></li></ul></div> <!----> <div class="eqc-content"><div class="eqc-head-sys"><div class="head-top"><ul class="list"><li class="item">全部</li></ul> <div class="icon close fr eqf-no"></div> <div class="icon search fr eqf-search-l"><span>搜索</span></div></div> <div class="head-bottom" style=""><div class="bottom-up" style="display: none;"><span class="name">分类：</span> <ul class="list"></ul></div> <div class="bottom-down"><span class="name">排序：</span> <ul class="list"><li class="item active">最新</li><li class="item">最热</li></ul> <span class="name price">价格：</span> <ul class="list"><li class="item active">全部</li><li class="item">免费</li><li class="item">1-10卡币</li><li class="item">11-20卡币</li><li class="item">21-30卡币</li></ul></div></div> <!----></div> <div class="eqc-image-list sys no-sub"><div class="wrap" style="display: none; overflow: hidden;"><ul class="list" style="transform: translate3d(0px, 0px, 0px);"></ul><div style="position: absolute; right: 2px; top: 0px; width: 8px; background: rgba(0, 0, 0, 0.4); border: 1px solid rgba(255, 255, 255, 0.2); border-radius: 4px; transition: background 0.3s ease 0s; display: none; transform: translate3d(0px, 0px, 0px);"></div></div> <div class="eqc-list-status"><span style="display: none;">加载中…</span> <div class="result" style=""><div class="box"></div> <span class="msg">没有筛选结果<br>换个条件再试试</span></div></div></div> <!---->
        </div>
    </div>
</div>
    
    
<script type="text/javascript" src="{{asset('static/js/2.5.13_vue.runtime.min.js')}}"></script>
<script type="text/javascript" src="{{asset('static/js/3.0.1_vue-router.min.js')}}"></script>
<script type="text/javascript" src="{{asset('static/js/3.0.1_vuex.min.js')}}"></script>
<script type="text/javascript" src="{{asset('static/js/0.17.1_axios.min.js')}}"></script>
<script type="text/javascript" src="{{asset('static/js/material/main-066465ee.js')}}"></script>
</body>


</html>