<?php

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\UnauthorizedException;

class Authenticate extends Middleware
{

    protected function authenticate($request, array $guards)
    {
        if (!Auth::user()) {
            $this->unauthenticated($request, $guards);
        }
        parent::authenticate($request, $guards); // TODO: Change the autogenerated stub
    }

    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param \Illuminate\Http\Request $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            return route('view.home') . '#login';
        }
    }

    protected function unauthenticated($request, array $guards)
    {
        throw new UnauthorizedException('用户未登录，请登录', 10);
    }
}
