<?php

namespace App\Models;

use Illuminate\Support\Facades\Storage;

class Music extends BaseModel
{
    protected $table = 'music';

    public function toArray()
    {
//        if (!empty($this->url)) {
//            $this->url = Storage::disk('scene')->url($this->url);
//        }
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
